### ISSUE TITLE
消息推送逻辑不完善

### ISSUE THREAD

**Issue by ifun666** [CCraftY/ZCMU_AUTO_PUNCH#1]
消息推送是通过判断是否填写钉钉机器人的Token和Secret进行判断是否进行推送，但事实上推送服务还有PushPlus等多种渠道，因此没有进行多维的综合判断。导致的结果是：如果仅需要通过PushPlus进行推送（只填写了PushPlus的Token）并不会进行推送。

**Comment by CCraftY** [comment]
> 消息推送是通过判断是否填写钉钉机器人的Token和Secret进行判断是否进行推送，但事实上推送服务还有PushPlus等多种渠道，因此没有进行多维的综合判断。导致的结果是：如果仅需要通过PushPlus进行推送（只填写了PushPlus的Token）并不会进行推送。
> 
> 另：我也是浙中医的，请加一下我的微信yinhuqiankun
正如Readme中所说，我也不是专业的，但我能想到的多用户推送只能在main中添加一块pushplus的代码了，所以就有了你的问题，你可以把那一块注释掉

**Comment by ifun666** [comment]
> > 消息推送是通过判断是否填写钉钉机器人的Token和Secret进行判断是否进行推送，但事实上推送服务还有PushPlus等多种渠道，因此没有进行多维的综合判断。导致的结果是：如果仅需要通过PushPlus进行推送（只填写了PushPlus的Token）并不会进行推送。
> > 另：我也是浙中医的，请加一下我的微信yinhuqiankun
> 
> 正如Readme中所说，我也不是专业的，但我能想到的多用户推送只能在main中添加一块pushplus的代码了，所以就有了你的问题，你可以把那一块注释掉

你是大几的呢？编程只是兴趣爱好？

**Comment by CCraftY** [comment]
> > > 消息推送是通过判断是否填写钉钉机器人的Token和Secret进行判断是否进行推送，但事实上推送服务还有PushPlus等多种渠道，因此没有进行多维的综合判断。导致的结果是：如果仅需要通过PushPlus进行推送（只填写了PushPlus的Token）并不会进行推送。
> > > 另：我也是浙中医的，请加一下我的微信yinhuqiankun
> > 
> > 
> > 正如Readme中所说，我也不是专业的，但我能想到的多用户推送只能在main中添加一块pushplus的代码了，所以就有了你的问题，你可以把那一块注释掉
> 
> 你是大几的呢？编程只是兴趣爱好？

大二哦，算是吧。刚好zstu和我们同一套系统，测试了几天把这个项目改好了

**Comment by ifun666** [comment]
> 

介意加个微信聊聊吗？

**Comment by ifun666** [comment]
> > > > 消息推送是通过判断是否填写钉钉机器人的Token和Secret进行判断是否进行推送，但事实上推送服务还有PushPlus等多种渠道，因此没有进行多维的综合判断。导致的结果是：如果仅需要通过PushPlus进行推送（只填写了PushPlus的Token）并不会进行推送。
> > > > 另：我也是浙中医的，请加一下我的微信yinhuqiankun
> > > 
> > > 
> > > 正如Readme中所说，我也不是专业的，但我能想到的多用户推送只能在main中添加一块pushplus的代码了，所以就有了你的问题，你可以把那一块注释掉
> > 
> > 
> > 你是大几的呢？编程只是兴趣爱好？
> 
> 大二哦，算是吧。刚好zstu和我们同一套系统，测试了几天把这个项目改好了

介意加个微信聊聊吗？
